# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.6

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force  # install Hex locally (without prompt)
      - run: mix local.rebar --force  # fetch a copy of rebar (without prompt)

      # specify any bash command here prefixed with `run: `
      # build tic_tac_toe
      - run: cd apps/tic_tac_toe && pwd
      - run: cd apps/tic_tac_toe && mix deps.get
      - run: cd apps/tic_tac_toe && mix test
      # build tic_tac_toe_hall
      - run: cd apps/tic_tac_toe_hall && pwd
      - run: cd apps/tic_tac_toe_hall && mix deps.get
      - run: cd apps/tic_tac_toe_hall && mix test
